[server]
address = "127.0.0.1:8800"
adminPort = 8801

[server.scheduleConf]
maxBatchSeqs = 25
maxBatchTokens = 1024
longPrefillTokenThreshold = 512
maxPartialPrefills = 2
maxLongPartialPrefills = 1
maxScheduleDelay = 30 # ms

[server.scheduleConf.queueConf]
queueLength = 100

[[executors]]
id = "mock-python"
kind = "connect"
address = ["http://127.0.0.1:19991"]
enabled = true

[[executors]]
id = "ollama-local"
kind = "http"
address = ["http://127.0.0.1:11434"]
enabled = false
