[runner]
executor_id = "executor-qwen3-0.6B"
model_id = "Qwen/Qwen3-0.6B"
model_path = "./models/Qwen3-0.6B"
dtype = "fp32" # "fp32/float32" | "fp16/float16" ...

[runtime]
device = "cpu"
tensor_parallel_size = 1
gpu_memory_utilization = 0.9
kv_cache_memory_bytes = 536870912 # 512 MiB, 0 means auto compute
