[server]
address = "127.0.0.1:8800"
adminPort = 8801

queueRoundTime = 30 # ms
queueLength = 1000

batchSize = 10
batchRoundDuration = 10 # ms

[[executors]]
id = "mock-python"
kind = "connect"
address = ["http://127.0.0.1:19991"]
enabled = true

[[executors]]
id = "ollama-local"
kind = "http"
address = ["http://127.0.0.1:11434"]
enabled = false
