# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: mini_llm_serve/v1/execute.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import mini_llm_serve.v1.execute_pb2 as mini__llm__serve_dot_v1_dot_execute__pb2


class ExecuteService(Protocol):
    async def execute_batch(self, request: mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ExecuteServiceASGIApplication(ConnectASGIApplication[ExecuteService]):
    def __init__(self, service: ExecuteService | AsyncGenerator[ExecuteService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/mini_llm_serve.v1.ExecuteService/ExecuteBatch": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="mini_llm_serve.v1.ExecuteService",
                        input=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
                        output=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_batch,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.ExecuteService"


class ExecuteServiceClient(ConnectClient):
    async def execute_batch(
        self,
        request: mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="mini_llm_serve.v1.ExecuteService",
                input=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
                output=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ExecuteServiceSync(Protocol):
    def execute_batch(self, request: mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ExecuteServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ExecuteServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/mini_llm_serve.v1.ExecuteService/ExecuteBatch": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="mini_llm_serve.v1.ExecuteService",
                        input=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
                        output=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_batch,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.ExecuteService"


class ExecuteServiceClientSync(ConnectClientSync):
    def execute_batch(
        self,
        request: mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="mini_llm_serve.v1.ExecuteService",
                input=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchRequest,
                output=mini__llm__serve_dot_v1_dot_execute__pb2.ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
