# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mini_llm_serve/v1/execute.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'mini_llm_serve/v1/execute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mini_llm_serve.v1 import core_pb2 as mini__llm__serve_dot_v1_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmini_llm_serve/v1/execute.proto\x12\x11mini_llm_serve.v1\x1a\x1cmini_llm_serve/v1/core.proto\"f\n\x13\x45xecuteBatchRequest\x12\x19\n\x08\x62\x61tch_id\x18\x01 \x01(\tR\x07\x62\x61tchId\x12\x34\n\x05items\x18\x02 \x03(\x0b\x32\x1e.mini_llm_serve.v1.ExecuteItemR\x05items\"|\n\x0b\x45xecuteItem\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n\nrequest_id\x18\x02 \x01(\tR\trequestId\x12\x16\n\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1d\n\nmax_tokens\x18\x04 \x01(\rR\tmaxTokens\"\x8e\x01\n\x14\x45xecuteBatchResponse\x12\x19\n\x08\x62\x61tch_id\x18\x01 \x01(\tR\x07\x62\x61tchId\x12\x1f\n\x0b\x65xecutor_id\x18\x02 \x01(\tR\nexecutorId\x12:\n\x07results\x18\x03 \x03(\x0b\x32 .mini_llm_serve.v1.ExecuteResultR\x07results\"\xbe\x02\n\rExecuteResult\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n\nrequest_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n\x0boutput_text\x18\x03 \x01(\tR\noutputText\x12\x44\n\rfinish_reason\x18\x04 \x01(\x0e\x32\x1f.mini_llm_serve.v1.FinishReasonR\x0c\x66inishReason\x12!\n\x0cinput_tokens\x18\x05 \x01(\rR\x0binputTokens\x12#\n\routput_tokens\x18\x06 \x01(\rR\x0coutputTokens\x12!\n\x0c\x65xecution_ms\x18\x07 \x01(\rR\x0b\x65xecutionMs\x12#\n\rerror_message\x18\x08 \x01(\tR\x0c\x65rrorMessage2q\n\x0e\x45xecuteService\x12_\n\x0c\x45xecuteBatch\x12&.mini_llm_serve.v1.ExecuteBatchRequest\x1a\'.mini_llm_serve.v1.ExecuteBatchResponseB\xd1\x01\n\x15\x63om.mini_llm_serve.v1B\x0c\x45xecuteProtoP\x01ZMgithub.com/qujing226/mini-llm-serve/gen/go/mini_llm_serve/v1;mini_llm_servev1\xa2\x02\x03MXX\xaa\x02\x0fMiniLlmServe.V1\xca\x02\x0fMiniLlmServe\\V1\xe2\x02\x1bMiniLlmServe\\V1\\GPBMetadata\xea\x02\x10MiniLlmServe::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mini_llm_serve.v1.execute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.mini_llm_serve.v1B\014ExecuteProtoP\001ZMgithub.com/qujing226/mini-llm-serve/gen/go/mini_llm_serve/v1;mini_llm_servev1\242\002\003MXX\252\002\017MiniLlmServe.V1\312\002\017MiniLlmServe\\V1\342\002\033MiniLlmServe\\V1\\GPBMetadata\352\002\020MiniLlmServe::V1'
  _globals['_EXECUTEBATCHREQUEST']._serialized_start=84
  _globals['_EXECUTEBATCHREQUEST']._serialized_end=186
  _globals['_EXECUTEITEM']._serialized_start=188
  _globals['_EXECUTEITEM']._serialized_end=312
  _globals['_EXECUTEBATCHRESPONSE']._serialized_start=315
  _globals['_EXECUTEBATCHRESPONSE']._serialized_end=457
  _globals['_EXECUTERESULT']._serialized_start=460
  _globals['_EXECUTERESULT']._serialized_end=778
  _globals['_EXECUTESERVICE']._serialized_start=780
  _globals['_EXECUTESERVICE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
