# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: mini_llm_serve/v1/service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import mini_llm_serve.v1.service_pb2 as mini__llm__serve_dot_v1_dot_service__pb2


class InferenceService(Protocol):
    async def generate(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def generate_stream(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest, ctx: RequestContext) -> AsyncIterator[mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InferenceServiceASGIApplication(ConnectASGIApplication[InferenceService]):
    def __init__(self, service: InferenceService | AsyncGenerator[InferenceService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/mini_llm_serve.v1.InferenceService/Generate": Endpoint.unary(
                    method=MethodInfo(
                        name="Generate",
                        service_name="mini_llm_serve.v1.InferenceService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate,
                ),
                "/mini_llm_serve.v1.InferenceService/GenerateStream": Endpoint.server_stream(
                    method=MethodInfo(
                        name="GenerateStream",
                        service_name="mini_llm_serve.v1.InferenceService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate_stream,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.InferenceService"


class InferenceServiceClient(ConnectClient):
    async def generate(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Generate",
                service_name="mini_llm_serve.v1.InferenceService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def generate_stream(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GenerateStream",
                service_name="mini_llm_serve.v1.InferenceService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class AdminService(Protocol):
    async def health(self, request: mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_runtime_stats(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceASGIApplication(ConnectASGIApplication[AdminService]):
    def __init__(self, service: AdminService | AsyncGenerator[AdminService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/mini_llm_serve.v1.AdminService/Health": Endpoint.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="mini_llm_serve.v1.AdminService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health,
                ),
                "/mini_llm_serve.v1.AdminService/GetRuntimeStats": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRuntimeStats",
                        service_name="mini_llm_serve.v1.AdminService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_runtime_stats,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.AdminService"


class AdminServiceClient(ConnectClient):
    async def health(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="mini_llm_serve.v1.AdminService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_runtime_stats(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntimeStats",
                service_name="mini_llm_serve.v1.AdminService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class InferenceServiceSync(Protocol):
    def generate(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def generate_stream(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest, ctx: RequestContext) -> Iterator[mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InferenceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: InferenceServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/mini_llm_serve.v1.InferenceService/Generate": EndpointSync.unary(
                    method=MethodInfo(
                        name="Generate",
                        service_name="mini_llm_serve.v1.InferenceService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate,
                ),
                "/mini_llm_serve.v1.InferenceService/GenerateStream": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="GenerateStream",
                        service_name="mini_llm_serve.v1.InferenceService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate_stream,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.InferenceService"


class InferenceServiceClientSync(ConnectClientSync):
    def generate(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Generate",
                service_name="mini_llm_serve.v1.InferenceService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def generate_stream(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GenerateStream",
                service_name="mini_llm_serve.v1.InferenceService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GenerateRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GenerateResponseChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AdminServiceSync(Protocol):
    def health(self, request: mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_runtime_stats(self, request: mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest, ctx: RequestContext) -> mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AdminServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AdminServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/mini_llm_serve.v1.AdminService/Health": EndpointSync.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="mini_llm_serve.v1.AdminService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health,
                ),
                "/mini_llm_serve.v1.AdminService/GetRuntimeStats": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRuntimeStats",
                        service_name="mini_llm_serve.v1.AdminService",
                        input=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
                        output=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_runtime_stats,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mini_llm_serve.v1.AdminService"


class AdminServiceClientSync(ConnectClientSync):
    def health(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="mini_llm_serve.v1.AdminService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.HealthRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_runtime_stats(
        self,
        request: mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntimeStats",
                service_name="mini_llm_serve.v1.AdminService",
                input=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsRequest,
                output=mini__llm__serve_dot_v1_dot_service__pb2.GetRuntimeStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
