apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-server-config
  namespace: mini-llm
  labels:
    app.kubernetes.io/name: mini-llm-server
    app.kubernetes.io/instance: demo
    app.kubernetes.io/component: server
data:
  server.toml: |
    [server]
    address = "0.0.0.0:8800"
    adminPort = 8801

    [server.scheduleConf]
    maxBatchSeqs = 25
    maxBatchTokens = 1024
    longPrefillTokenThreshold = 512
    maxPartialPrefills = 2
    maxLongPartialPrefills = 1

    [server.scheduleConf.queueConf]
    queueRoundTime = 30 # ms
    queueLength = 100

    [[executors]]
    id = "mock-executor-0"
    kind = "connect"
    address = ["http://mock-executor:19991"]
    enabled = true

    [[executors]]
    id = "mock-executor-1"
    kind = "connect"
    address = ["http://mock-executor:19991"]
    enabled = true

    [[executors]]
    id = "mock-executor-2"
    kind = "connect"
    address = ["http://mock-executor:19991"]
    enabled = true
