apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-server
  namespace: mini-llm
  labels:
    app.kubernetes.io/name: mini-llm-server
    app.kubernetes.io/instance: demo
    app.kubernetes.io/component: server
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: mini-llm.local
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: demo-server
                port:
                  name: admin
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-server
                port:
                  name: inference
